POST http://localhost:3000/api/seasons
Content-Type: application/json

{
  "name": "Dussehra 2025"
}


###
GET http://localhost:3000/api/seasons


###
POST http://localhost:3000/api/matches
Content-Type: application/json

{
  "seasonId": "1767638293796",
  "teamA": "Team Blue",
  "teamB": "Team Red",
  "matchType": "LIMITED"
}

###
GET http://localhost:3000/api/matches/season/1767638293796

